### ISSUE TITLE
Issues with the Atari ST core on the Mister FPGA - bizarrely no issues on the Amiga core

### ISSUE THREAD

**Issue by spikemorrissey** [devonshire/arduino-atari-hid-keyboard#3]
I have recreated this very clever project connected to an Atari ST

When connected to my PC all keys work as they should

When connected to the Mister FPGA , the keys mostly work - however one has to hold down the key for a second or two to register the keypress which I don't mind too much.
The issue however is with games on the ST core - most of them rely on the numeric keypad namely * and / to save and quit
however on the Mister these aren't registering at all.

As an update to this - when I use this on Minimig also on the Mister FPGA, the keypresses are in realtime and the numeric keypad works as it should!

Does anyone have a solution for this please?

**Comment by M1kerochip** [comment]
I forked the project, and fixed all the numberpad keys with the correct key presses.

https://github.com/M1kerochip/arduino-atari-hid-keyboard

**Comment by spikemorrissey** [comment]
Hi, Thank you so much for attempting a solution to this. Unfortunately after  I uploaded your fork of the project I can't get any keys at all to function on my keyboard on both the Atari ST Mister FPGA and on my PC. I re-uploaded the original program and everything works as before (with the same issues). I would love to have the correct keys working, perhaps I am doing something wrong?

**Comment by M1kerochip** [comment]
I've changed the default pins, to match a PCB I'm building.

If you've got my source, change the line 111 from const int ST_KB_RESET = 8;
to
const int ST_KB_RESET = 4;

Or, you can change your wiring to match.
I also added Digital Pin 9, connected to the Floppy LED, and it lets you use the floppy led as a capslock led :)

The only keys I couldn't set properly were ( and ) on the number pad. The arduino keyboard source doesn't allow for it.

I've also defined 3 layouts, for 3 different ST keyboards:
UK, DE and US.

To define other layouts, I'd have to see their ST keyboards.

**Comment by spikemorrissey** [comment]
Hi, Thank you so much. It works perfectly now!
